// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAuctions.Persistence.Context;

#nullable disable

namespace WebAuctions.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20231019172556_InitialE")]
    partial class InitialE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("WebAuctions.Persistence.AuctionDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bid")
                        .HasMaxLength(128)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuctionDBs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Bid = 50.0,
                            Date = new DateTime(2023, 10, 19, 19, 25, 56, 744, DateTimeKind.Local).AddTicks(6350),
                            Duration = 3,
                            ItemName = "Large Tent",
                            Status = 0,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("WebAuctions.Persistence.ItemDB", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ItemDBs");

                    b.HasData(
                        new
                        {
                            Name = "Large Tent",
                            Description = "A Large Tent",
                            Picture = "images/tent1.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
