// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAuctions.Persistence.Context;

#nullable disable

namespace WebAuctions.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("WebAuctions.Persistence.AuctionDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bid")
                        .HasMaxLength(128)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuctionDBs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Bid = 50.0,
                            Date = new DateTime(2023, 10, 19, 13, 18, 45, 461, DateTimeKind.Local).AddTicks(6490),
                            Duration = 3,
                            ItemName = "Large Tent",
                            Status = 0,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("WebAuctions.Persistence.ItemDB", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ItemDBs");

                    b.HasData(
                        new
                        {
                            Name = "Large Tent",
                            Description = "A Large Tent",
                            Picture = "images/tent1.png"
                        });
                });

            modelBuilder.Entity("WebAuctions.Persistence.UserDB", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Permission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserDBs");

                    b.HasData(
                        new
                        {
                            UserId = -1,
                            Password = "password",
                            Permission = 0,
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
